// Code generated by go-swagger; DO NOT EDIT.

package fsm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddFSMHandlerFunc turns a function with the right signature into a add f s m handler
type AddFSMHandlerFunc func(AddFSMParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddFSMHandlerFunc) Handle(params AddFSMParams) middleware.Responder {
	return fn(params)
}

// AddFSMHandler interface for that can handle valid add f s m params
type AddFSMHandler interface {
	Handle(AddFSMParams) middleware.Responder
}

// NewAddFSM creates a new http.Handler for the add f s m operation
func NewAddFSM(ctx *middleware.Context, handler AddFSMHandler) *AddFSM {
	return &AddFSM{Context: ctx, Handler: handler}
}

/*AddFSM swagger:route POST / fsm addFSM

Create a new fsm

*/
type AddFSM struct {
	Context *middleware.Context
	Handler AddFSMHandler
}

func (o *AddFSM) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddFSMParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
