// Code generated by go-swagger; DO NOT EDIT.

package fsm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/batazor/fsme/admin/server/models"
)

// DestroyFSMNoContentCode is the HTTP code returned for type DestroyFSMNoContent
const DestroyFSMNoContentCode int = 204

/*DestroyFSMNoContent Deleted

swagger:response destroyFSMNoContent
*/
type DestroyFSMNoContent struct {
}

// NewDestroyFSMNoContent creates DestroyFSMNoContent with default headers values
func NewDestroyFSMNoContent() *DestroyFSMNoContent {

	return &DestroyFSMNoContent{}
}

// WriteResponse to the client
func (o *DestroyFSMNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DestroyFSMDefault error

swagger:response destroyFSMDefault
*/
type DestroyFSMDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDestroyFSMDefault creates DestroyFSMDefault with default headers values
func NewDestroyFSMDefault(code int) *DestroyFSMDefault {
	if code <= 0 {
		code = 500
	}

	return &DestroyFSMDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the destroy f s m default response
func (o *DestroyFSMDefault) WithStatusCode(code int) *DestroyFSMDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the destroy f s m default response
func (o *DestroyFSMDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the destroy f s m default response
func (o *DestroyFSMDefault) WithPayload(payload *models.Error) *DestroyFSMDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the destroy f s m default response
func (o *DestroyFSMDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DestroyFSMDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
