// Code generated by go-swagger; DO NOT EDIT.

package fsm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/batazor/fsme/admin/server/models"
)

// GetFSMListOKCode is the HTTP code returned for type GetFSMListOK
const GetFSMListOKCode int = 200

/*GetFSMListOK get list the fsm

swagger:response getFSMListOK
*/
type GetFSMListOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Fsm `json:"body,omitempty"`
}

// NewGetFSMListOK creates GetFSMListOK with default headers values
func NewGetFSMListOK() *GetFSMListOK {

	return &GetFSMListOK{}
}

// WithPayload adds the payload to the get f s m list o k response
func (o *GetFSMListOK) WithPayload(payload []*models.Fsm) *GetFSMListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get f s m list o k response
func (o *GetFSMListOK) SetPayload(payload []*models.Fsm) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFSMListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Fsm, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetFSMListDefault generic error response

swagger:response getFSMListDefault
*/
type GetFSMListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFSMListDefault creates GetFSMListDefault with default headers values
func NewGetFSMListDefault(code int) *GetFSMListDefault {
	if code <= 0 {
		code = 500
	}

	return &GetFSMListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get f s m list default response
func (o *GetFSMListDefault) WithStatusCode(code int) *GetFSMListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get f s m list default response
func (o *GetFSMListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get f s m list default response
func (o *GetFSMListDefault) WithPayload(payload *models.Error) *GetFSMListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get f s m list default response
func (o *GetFSMListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFSMListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
