// Code generated by go-swagger; DO NOT EDIT.

package fsm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateFSMHandlerFunc turns a function with the right signature into a update f s m handler
type UpdateFSMHandlerFunc func(UpdateFSMParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateFSMHandlerFunc) Handle(params UpdateFSMParams) middleware.Responder {
	return fn(params)
}

// UpdateFSMHandler interface for that can handle valid update f s m params
type UpdateFSMHandler interface {
	Handle(UpdateFSMParams) middleware.Responder
}

// NewUpdateFSM creates a new http.Handler for the update f s m operation
func NewUpdateFSM(ctx *middleware.Context, handler UpdateFSMHandler) *UpdateFSM {
	return &UpdateFSM{Context: ctx, Handler: handler}
}

/*UpdateFSM swagger:route PATCH /{_id} fsm updateFSM

Update a fsm

*/
type UpdateFSM struct {
	Context *middleware.Context
	Handler UpdateFSMHandler
}

func (o *UpdateFSM) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateFSMParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
