/**
 * FSME
 * FSME server for UI
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Fsme) {
      root.Fsme = {};
    }
    root.Fsme.Fsm = factory(root.Fsme.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Fsm model module.
   * @module model/Fsm
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Fsm</code>.
   * @alias module:model/Fsm
   * @class
   * @param rules {String} 
   */
  var exports = function(rules) {
    var _this = this;



    _this['rules'] = rules;



  };

  /**
   * Constructs a <code>Fsm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fsm} obj Optional instance to populate.
   * @return {module:model/Fsm} The populated <code>Fsm</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('rules')) {
        obj['rules'] = ApiClient.convertToType(data['rules'], 'String');
      }
      if (data.hasOwnProperty('events')) {
        obj['events'] = ApiClient.convertToType(data['events'], 'String');
      }
      if (data.hasOwnProperty('callbacks')) {
        obj['callbacks'] = ApiClient.convertToType(data['callbacks'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} rules
   */
  exports.prototype['rules'] = undefined;
  /**
   * @member {String} events
   */
  exports.prototype['events'] = undefined;
  /**
   * @member {String} callbacks
   */
  exports.prototype['callbacks'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;



  return exports;
}));


