/**
 * FSME
 * FSME server for UI
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Fsm model module.
* @module model/Fsm
* @version 0.1.0
*/
export default class Fsm {
    /**
    * Constructs a new <code>Fsm</code>.
    * @alias module:model/Fsm
    * @class
    * @param rules {String} 
    */

    constructor(rules) {
        

        
        

        this['rules'] = rules;

        
    }

    /**
    * Constructs a <code>Fsm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Fsm} obj Optional instance to populate.
    * @return {module:model/Fsm} The populated <code>Fsm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Fsm();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('rules')) {
                obj['rules'] = ApiClient.convertToType(data['rules'], 'String');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], 'String');
            }
            if (data.hasOwnProperty('callbacks')) {
                obj['callbacks'] = ApiClient.convertToType(data['callbacks'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {String} rules
    */
    rules = undefined;
    /**
    * @member {String} events
    */
    events = undefined;
    /**
    * @member {String} callbacks
    */
    callbacks = undefined;
    /**
    * @member {String} state
    */
    state = undefined;








}


