// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Create a new Error
func (m *Error) Create(b []byte) error {

}

// Get by Id
func (m *Error) GetById(b []byte) error {

}

// Get list
func (m *Error) GetList(b []byte) error {

}

// Update
func (m *Error) Update(b []byte) error {

}

// Delete
func (m *Error) Destroy(b []byte) error {

}
