// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Create a new Event
func (m *Event) Create(b []byte) error {

}

// Get by Id
func (m *Event) GetById(b []byte) error {

}

// Get list
func (m *Event) GetList(b []byte) error {

}

// Update
func (m *Event) Update(b []byte) error {

}

// Delete
func (m *Event) Destroy(b []byte) error {

}
