// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Create a new Fsm
func (m *Fsm) Create(b []byte) error {

}

// Get by Id
func (m *Fsm) GetById(b []byte) error {

}

// Get list
func (m *Fsm) GetList(b []byte) error {

}

// Update
func (m *Fsm) Update(b []byte) error {

}

// Delete
func (m *Fsm) Destroy(b []byte) error {

}
