/**
 * FSME
 * FSME server for UI
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Fsme);
  }
}(this, function(expect, Fsme) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Fsme.FsmApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FsmApi', function() {
    describe('addFSM', function() {
      it('should call addFSM successfully', function(done) {
        //uncomment below and update the code to test addFSM
        //instance.addFSM(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('destroyFSM', function() {
      it('should call destroyFSM successfully', function(done) {
        //uncomment below and update the code to test destroyFSM
        //instance.destroyFSM(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFSM', function() {
      it('should call getFSM successfully', function(done) {
        //uncomment below and update the code to test getFSM
        //instance.getFSM(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFSMList', function() {
      it('should call getFSMList successfully', function(done) {
        //uncomment below and update the code to test getFSMList
        //instance.getFSMList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateFSM', function() {
      it('should call updateFSM successfully', function(done) {
        //uncomment below and update the code to test updateFSM
        //instance.updateFSM(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
