// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi FSME
FSME server for UI


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/io.goswagger.examples.todo-list.v1+json

    Produces:
    - application/io.goswagger.examples.todo-list.v1+json

swagger:meta
*/
package restapi
